services:
  postgres:
    image: postgres:16
    container_name: station_postgres_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: dbstorer
      POSTGRES_PASSWORD: le!2d4pa$elpas?sword123
      POSTGRES_DB: stationsdb

    # Expose port on host
    ports:
      - "5442:5432"

    # Persistent volume for DB files
    volumes:
      - mainnode_postgres_data:/var/lib/postgresql/data

volumes:
  mainnode_postgres_data:
    driver: local

# docker run -d --name ledpanel-postgres -e POSTGRES_USER=dbstorer -e POSTGRES_PASSWORD='le!2d4pa$elpas?sword123' -e POSTGRES_DB=stationsdb -p 5442:5432 -v ledpanel-postgres-data:/var/lib/postgresql/data postgres:16