led-gpio-mapping=regular
led-rows=64
led-cols=64
led-chain=3
led-parallel=1
led-multiplexing=0
led-pixel-mapper=U-mapper
led-pwb-bits=16
led-brightness=80
led-scan-mode=0
led-row-addr-type=0
led-slowdown-gpio=2